ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

- Adds a flag indicating that the call is coming from the mobile SDK. We still need this to determine the mobile SDK case vs the mobile web browser case, but we don't care about the device type (tablet vs. phone)
- https://ketch-com.atlassian.net/browse/KD-11869

feat: add mobile sdk flag

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt

> Adds an `onConsentUpdated` listener to the android SDK
- Local

feat: add on consent updated listener

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt

KD-13169 Crash when activity is inactive
KD-13168 Android SDK Memory Leak

KD-13169 Crash when activity is inactive

---

ketchsdk/src/main/AndroidManifest.xml

> Use the correct feature name in the uses-feature manifest statement. The previous one was incorrect and prevented customers from releasing their app
- https://ketch-com.slack.com/archives/C06JKD9F3K7/p1720555803644709

fix: use correct name for webview in feature requirement

---

ketchsdk/src/main/java/com/ketch/android/ui/KetchDialogFragment.kt

> Sets the webview reference to null in `onDestroyView` to avoid a memory leak
- https://ketch-com.atlassian.net/browse/KD-13477

fix: memory leak

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt

> Fixes a memory leak caused by our `FragmentManager` not using a `WeakReference`
- Local with android sample app

fix: fragment manager memory leak

---

ketchsdk/build.gradle
ketchsdk/src/main/java/com/ketch/android/KetchSharedPreferences.kt

> Update the shared preferences file name and format of various values
- Local on sample app

fix(shared-prefs): tcf string format and file name

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

> Fixes a memory leak in the `Ketch` class and uses a thread safe boolean in `KetchWebView`
- Locally with sample application

fix: memory leak and thread safe boolean

---

ketchsdk/src/main/java/com/ketch/android/KetchSharedPreferences.kt

> For any decimal types, cast them to int so the values match the [IAB TCF standards](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md)
- Local with sample app

fix: cast decimal types to int

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt

> Adds the retry param which we use in the other display methods to the `showPreferencesTab` method

feat: add retry to the showPreferencesTab method

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt

> Returns a boolean indicating the success/failure of webview creation
- Locally in testing app

feat: return boolean with loading result

---

build.gradle
ketchsdk/build.gradle

> Removes unused material dependency

chore: remove legacy material dep

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt
ketchsdk/src/main/java/com/ketch/android/data/Index.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

> Adds param for passing a custom bottom padding to the bottom of the experience

feat: bottom padding param

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt
ketchsdk/src/main/java/com/ketch/android/data/Index.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

feat: topPadding variable

---

ketchsdk/build.gradle

> Adds pom block with license info, to address issues using the SDK in strict mode apps
- https://ketch-com.slack.com/archives/C082FDXG54Z/p1745949913573079

chore: add POM block with license info

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt
ketchsdk/src/main/java/com/ketch/android/data/Index.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

Supports custom css style

---

ketchsdk/src/main/java/com/ketch/android/Ketch.kt
ketchsdk/src/main/java/com/ketch/android/data/Index.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchDialogFragment.kt
ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt
ketchsdk/src/main/res/layout/ketch_dialog_layout.xml

> Fixes issue causing premature webview garbage collection
- Sample app
- https://ketch-com.atlassian.net/browse/KD-15603

fix(webview-creation): garbage collection issues

---

ketchsdk/src/main/java/com/ketch/android/ui/KetchWebView.kt

> Fixes crash when opening experience URLs in apache cordova apps
- Sample app
- https://ketch-com.atlassian.net/browse/KD-15648

fix(apache-cordova): crash when opening URLs

---

build.gradle
gradle/wrapper/gradle-wrapper.properties
ketchsdk/build.gradle

KD-15650: updated SDK dependencies

---

build.gradle

KD-15650: additional dependabot warnings fixes in SDK

---

.gitignore
integration-tests/README.md
integration-tests/build.gradle
integration-tests/proguard-rules.pro
integration-tests/src/androidTest/java/com/ketch/android/integration/tests/KetchSdkIntegrationTest.kt
integration-tests/src/main/AndroidManifest.xml
integration-tests/src/main/java/com/ketch/android/integration/tests/MainActivity.kt
integration-tests/src/main/res/drawable/ic_launcher_background.xml
integration-tests/src/main/res/drawable/ic_launcher_foreground.xml
integration-tests/src/main/res/layout/activity_main.xml
integration-tests/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
integration-tests/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
integration-tests/src/main/res/values/colors.xml
integration-tests/src/main/res/values/strings.xml
integration-tests/src/main/res/values/themes.xml
integration-tests/src/main/res/xml/backup_rules.xml
integration-tests/src/main/res/xml/data_extraction_rules.xml
integration-tests/src/main/res/xml/network_security_config.xml
run-integration-tests.sh
settings.gradle

This PR adds a integration test suite to verify the android SDKs functionality in an android application.
- **Sample App**: `MainActivity` with buttons for all SDK methods and real-time status display
- **Integration Tests**: `KetchSdkIntegrationTest` with comprehensive test methods
- **Test Runner**: `run-integration-tests.sh` script for easy execution
The tests validate the SDK's core functionality including dialog display, user interactions, consent state management, and proper callback execution.
- **Device**: Android emulator and physical devices (API 28+)
- **Framework**: Espresso for UI testing, AndroidX Test for infrastructure
1. **All Tests**: Run `./run-integration-tests.sh` or `./gradlew :integration-tests:connectedAndroidTest` for complete test execution
2. **Specific Test**: …

feat(testing): integration test suite
